#!/usr/bin/env python
import sys
import os

import torch

sys.path.append('Replace the path in your folder./ENV')
import rospy
from std_msgs.msg import Float32
from environment_slam import Env
import numpy as np
import copy


# ---Directory Path---#
dirPath = os.path.dirname(os.path.realpath(__file__))

if __name__ == '__main__':
    rospy.init_node('main')
    # pub_result = rospy.Publisher('result', Float32, queue_size=5)
    # result = Float32()
  
    action_dim = 2
    state_dim = 30
    max_steps = 500
    past_action = np.array([0., 0.])
    results = []

    train_reward = np.empty((0, 3), float)
    test_reward = np.empty((0, 3), float)

    env = Env(action_dim)

    state = env.reset()

    # rewards_current_episode = 0.
    
    
